name: custom_rating_bar
description: Custom rating bar for flutter with support of custom icons, half icons, directions, alignments & more.
version: 1.0.0
homepage: https://github.com/marcsanny/custom_rating_bar

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter